### ISSUE TITLE
Currently the SSH Key Pair isn't used by the worker nodes

### ISSUE THREAD

**Issue by cablespaghetti** [anmolnagpal/terraform-eks#4]
Just going over this to steal some ideas I noticed that the aws_key_pair isn't actually used in the launch configuration.

**Comment by anmolnagpal** [comment]
Hello @cablespaghetti,

Yes, you are right. I'll remove it now if you want to create a pull request let me know.
Thanks

**Comment by cablespaghetti** [comment]
Unfortunately I've got my own similar project I started last week (not on github). I'm working on spot fleet support at the moment. When I've got it working I'll see if I can send some PRs your way.

**Comment by anmolnagpal** [comment]
Cool, Thank You @cablespaghetti

**Comment by anmolnagpal** [comment]
Fixed
