### ISSUE TITLE
cluster.tf -- Incorrect attribute value type

### ISSUE THREAD

**Issue by achede22** [anmolnagpal/terraform-eks#9]
# terraform plan -out=plan.tr
provider.aws.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.

  Enter a value: us-east-1

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.aws_region.current: Refreshing state...
data.aws_availability_zones.available: Refreshing state...

------------------------------------------------------------------------

Error: Incorrect attribute value type

  on cluster.tf line 52, in resource "aws_eks_cluster" "eks-cluster":
  52:     subnet_ids = [

Inappropriate value for attribute "subnet_ids": element 0: string required.

**Comment by akarokr** [comment]
What terraform version are you using? This seems to be a issue with the newest version, try it to downgrade to 0.11.14. I had the same problem.
